# Generated by Django 4.2.18 on 2025-02-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(choices=[(1, '1 уровень (+400р)'), (2, '2 уровня (+750р)'), (3, '3 уровня (+1100р)')])),
                ('form', models.CharField(choices=[('square', 'Квадрат (+600)'), ('circle', 'Круг (+400)'), ('rectangle', 'Прямоугольник (+1000)')], max_length=20)),
                ('topping', models.CharField(choices=[('none', 'Без топпинга'), ('white_sauce', 'Белый соус (+200)'), ('caramel', 'Карамельный сироп (+180)'), ('maple', 'Кленовый сироп (+200)'), ('strawberry', 'Клубничный сироп (+300)'), ('blueberry', 'Черничный сироп (+350)'), ('chocolate', 'Молочный шоколад (+200)')], max_length=20)),
                ('berries', models.CharField(blank=True, max_length=20, null=True)),
                ('decor', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('urgent_delivery', models.BooleanField(default=False)),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('privacy_agreement', models.FileField(blank=True, null=True, upload_to='privacy_agreements/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cakes', models.ManyToManyField(to='data.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('contact_info', models.TextField()),
                ('cake_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
    ]
