# Generated by Django 4.2.18 on 2025-02-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user_privacy_agreement_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('processing', 'Ожидает обработки'), ('in_progress', 'В процессе доставки'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='data.order')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryReport',
        ),
    ]
