# Generated by Django 4.2.18 on 2025-02-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delivery_delete_deliveryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='delivery_time',
        ),
    ]
