# Generated by Django 4.2.18 on 2025-02-27 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_cake_address_remove_cake_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='urgent_delivery',
            new_name='is_urgent',
        ),
        migrations.AddField(
            model_name='cake',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(choices=[('none', 'Без ягод'), ('blackberry', 'Ежевика (+400р)'), ('raspberry', 'Малина (+300р)'), ('blueberry', 'Голубика (+450р)'), ('strawberry', 'Клубника (+500р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(choices=[('none', 'Без декора'), ('pistachio', 'Фисташки (+300р)'), ('meringue', 'Безе (+400р)'), ('hazelnut', 'Фундук (+350р)'), ('pecan', 'Пекан (+300р)'), ('marshmallow', 'Маршмеллоу (+200р)'), ('marzipan', 'Марципан (+280р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.CharField(choices=[('circle', 'Круг (+400р)'), ('square', 'Квадрат (+600р)'), ('rectangle', 'Прямоугольник (+1000р)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[('none', 'Без топпинга'), ('white', 'Белый соус (+200р)'), ('caramel', 'Карамельный сироп (+180р)'), ('maple', 'Кленовый сироп (+200р)'), ('strawberry', 'Клубничный сироп (+300р)'), ('blueberry', 'Черничный сироп (+350р)'), ('chocolate', 'Молочный шоколад (+200р)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
