# Generated by Django 4.2.18 on 2025-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_urgent_delivery_cake_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/', verbose_name='Фото торта'),
        ),
    ]
