# Generated by Django 4.2.18 on 2025-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_cake_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
