# Generated by Django 4.2.18 on 2025-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='.cakes/', verbose_name='Фото торта'),
        ),
    ]
