# Generated by Django 4.2.18 on 2025-03-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_user_telegram_id'),
        ('data', '0014_alter_cake_photo'),
    ]

    operations = [
    ]
