# Generated by Django 4.2.18 on 2025-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_merge_20250301_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(choices=[('none', 'Без ягод'), ('none', 'Без ягод (+0)'), ('blackberry', 'Ежевика (+400р)'), ('raspberry', 'Малина (+300р)'), ('blueberry', 'Голубика (+450р)'), ('strawberry', 'Клубника (+500р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(choices=[('none', 'Без декора'), ('none', 'Без декора (+0)'), ('pistachio', 'Фисташки (+300р)'), ('meringue', 'Безе (+400р)'), ('hazelnut', 'Фундук (+350р)'), ('pecan', 'Пекан (+300р)'), ('marshmallow', 'Маршмеллоу (+200р)'), ('marzipan', 'Марципан (+280р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels',
            field=models.IntegerField(choices=[(1, '1 уровень (+400р)'), (2, '2 уровня (+750р)'), (3, '3 уровня (+1100р)'), (1, 'Первый уровень (+400р)'), (2, 'Второй уровень (+750р)'), (3, 'Третий уровень (+1100р)')]),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[('none', 'Без топпинга'), ('none', 'Без топпинга (+0)'), ('white', 'Белый соус (+200р)'), ('caramel', 'Карамельный сироп (+180р)'), ('maple', 'Кленовый сироп (+200р)'), ('strawberry', 'Клубничный сироп (+300р)'), ('blueberry', 'Черничный сироп (+350р)'), ('chocolate', 'Молочный шоколад (+200р)')], max_length=20),
        ),
    ]
