# Generated by Django 5.1.6 on 2025-03-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_promocode_alter_cake_berries_alter_cake_decor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_agreement',
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(choices=[('без', 'Без ягод (+0)'), ('ежевика', 'Ежевика (+400р)'), ('малина', 'Малина (+300р)'), ('голубика', 'Голубика (+450р)'), ('клубника', 'Клубника (+500р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(choices=[('без', 'Без декора (+0)'), ('фисташки', 'Фисташки (+300р)'), ('безе', 'Безе (+400р)'), ('фундук', 'Фундук (+350р)'), ('пекан', 'Пекан (+300р)'), ('маршмеллоу', 'Маршмеллоу (+200р)'), ('марципан', 'Марципан (+280р)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.CharField(choices=[('круг', 'Круг (+400р)'), ('квадрат', 'Квадрат (+600р)'), ('прямоугольник', 'Прямоугольник (+1000р)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels',
            field=models.IntegerField(choices=[(1, 'Первый уровень (+400р)'), (2, 'Второй уровень (+750р)'), (3, 'Третий уровень (+1100р)')]),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[('без', 'Без топпинга (+0)'), ('белый', 'Белый соус (+200р)'), ('карамельный', 'Карамельный сироп (+180р)'), ('кленовый', 'Кленовый сироп (+200р)'), ('клубничный', 'Клубничный сироп (+300р)'), ('черничный', 'Черничный сироп (+350р)'), ('шоколадный', 'Молочный шоколад (+200р)')], max_length=20),
        ),
    ]
