# Generated by Django 5.1.6 on 2025-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_user_privacy_agreement_alter_cake_berries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
