# Generated by Django 5.1.6 on 2025-03-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_cake_purchase_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='purchase_count',
        ),
    ]
