# Generated by Django 5.1.6 on 2025-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_purchase_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
