# Generated by Django 5.1.6 on 2025-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название торта')),
                ('description', models.TextField(verbose_name='Описание торта')),
                ('ingredients', models.TextField(help_text='Перечислите ингредиенты через запятую', verbose_name='Состав торта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='ready_cakes/', verbose_name='Изображение торта')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
            ],
        ),
        migrations.RemoveField(
            model_name='cake',
            name='name',
        ),
    ]
