# Generated by Django 5.1.6 on 2025-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_readycake_remove_cake_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
