# Generated by Django 5.1.6 on 2025-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_remove_promocode_is_active_alter_promocode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
            ],
        ),
    ]
